name: Browser-test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: firefox

      - name: cypress-Test Reprots
        uses: actions/upload-artifact@v4
        with:
          path: cypress\reports\html
